apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext443
  labels:
    app: BoundedContext443
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext443
  template:
    metadata:
      labels:
        app: BoundedContext443
    spec:
      containers:
        - name: BoundedContext443
          image: "username/BoundedContext443:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
